# Generated by Django 5.1.6 on 2025-09-26 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brewery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("year_founded", models.IntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Breweries",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Beer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("IPA", "India Pale Ale"),
                            ("DIPA", "Double IPA"),
                            ("STOUT", "Stout"),
                            ("PORTER", "Porter"),
                            ("LAGER", "Lager"),
                            ("PILSNER", "Pilsner"),
                            ("WHEAT", "Wheat Beer"),
                            ("SOUR", "Sour"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "abv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Alcohol By Volume %",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "ibu",
                    models.IntegerField(
                        blank=True,
                        help_text="International Bitterness Units",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brewery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beers",
                        to="taps.brewery",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="beers", to="taps.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
