# Generated by Django 5.1.6 on 2025-02-14 21:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Alcohol By Volume %', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(blank=True, help_text='International Bitterness Units', null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.CharField(choices=[('IPA', 'India Pale Ale'), ('DIPA', 'Double IPA'), ('STOUT', 'Stout'), ('PORTER', 'Porter'), ('LAGER', 'Lager'), ('PILSNER', 'Pilsner'), ('WHEAT', 'Wheat Beer'), ('SOUR', 'Sour'), ('OTHER', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brewery',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='brewery',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='taps.brewery'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
