# Generated by Django 3.1.5 on 2021-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='beers',
        ),
        migrations.AddField(
            model_name='beer',
            name='tags',
            field=models.ManyToManyField(to='taps.Tag'),
        ),
    ]
