# Generated by Django 5.1.6 on 2025-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0003_savedbeer"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewery",
            name="address_1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="brewery",
            name="address_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="brewery",
            name="city",
            field=models.CharField(default="Fake", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brewery",
            name="country",
            field=models.CharField(default="United States", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brewery",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="external_source",
            field=models.CharField(
                blank=True,
                choices=[("OPEN_BREWERY_DB", "Open Brewery Db")],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="brewery",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="brewery",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="brewery",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="brewery",
            name="state_province",
            field=models.CharField(default="Massachusetts", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brewery",
            name="website",
            field=models.URLField(),
        ),
    ]
