# Generated by Django 5.1.6 on 2025-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0003_savedbeer"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewery",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="external_source",
            field=models.CharField(
                blank=True, choices=[("OPEN_BREWERY_DB", "Open Brewery Db")]
            ),
        ),
    ]
