# Generated by Django 3.1.5 on 2021-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0003_auto_20210123_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewery',
            options={'verbose_name_plural': 'Breweries'},
        ),
        migrations.AddField(
            model_name='tag',
            name='beers',
            field=models.ManyToManyField(to='taps.Beer'),
        ),
    ]
