# Generated by Django 5.1.6 on 2025-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0003_savedbeer"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewery",
            name="address_1",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="brewery",
            name="address_2",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="brewery",
            name="city",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="external_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="brewery",
            name="external_source",
            field=models.CharField(
                blank=True, choices=[("OPEN_BREWERY_DB", "Open Brewery Db")]
            ),
        ),
        migrations.AddField(
            model_name="brewery",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="brewery",
            name="state_province",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
