# Generated by Django 3.1.5 on 2021-01-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0004_auto_20210123_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='taps.Tag'),
        ),
    ]
