# Generated by Django 5.1.6 on 2025-11-18 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taps", "0004_brewery_address_1_brewery_address_2_brewery_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brewery",
            name="location",
        ),
    ]
