# Generated by Django 3.1.5 on 2021-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0005_auto_20210123_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='beers',
        ),
        migrations.AlterField(
            model_name='beer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='beers', to='taps.Tag'),
        ),
    ]
