matrix:
  include:
    - language: node_js
      node_js:
        - "lts/*"
      cache:
        directories:
          - "$HOME/.npm"
      before_install:
        - cd client
      install:
        - npm ci
      script:
        # Run prettier format check
        - npm run format:check
        # Run linter
        - npm run lint
        # Run tests
        - npm test
