name: taps
version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    # Uncomment below to enable query logging
    # command: postgres -c log_statement=all -c log_destination=stderr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    env_file: .env
    build:
      context: ./taps-backend
      dockerfile: Dockerfile
      target: dev
      args:
        # References env vars in .env file
        SECRET_KEY: ${SECRET_KEY}
        DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./taps-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/graphql
    depends_on:
      - backend

volumes:
  postgres_data:
