name: Deploy Taps Application (Staging)

on:
  pull_request:
    types: [opened, synchronize, labeled]
  workflow_dispatch:

jobs:
  deploy:
    if: contains(github.event.pull_request.labels.*.name, 'deploy-staging')
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: staging
      image_tag: staging-pr${{ github.event.pull_request.number }}-${{ github.sha }}
      commit_hash: ${{ github.sha }}
      frontend_api_url: https://api-staging.taps.dillonkerr.com/graphql
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
