name: Deploy Taps Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-reusable.yml
    with:
      environment: production
      image_tag: ${{ github.sha }}
      frontend_api_url: https://api.taps.dillonkerr.com/graphql
    secrets:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
