name: PR Checks

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test-frontend:
    uses: ./.github/workflows/test-frontend.yml

  test-backend:
    uses: ./.github/workflows/test-backend.yml

  test-infrastructure:
    uses: ./.github/workflows/test-infrastructure.yml
