name: PR Checks

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      test-frontend:
        if: contains(github.event.pull_request.labels.*.name, 'deploy-staging')
        uses: ./.github/workflows/test-frontend.yml

      test-backend:
        if: contains(github.event.pull_request.labels.*.name, 'deploy-staging')
        uses: ./.github/workflows/test-backend.yml
